var cards = require('./cards.js');

var allCards = module.exports.allCards = function() {
    return [
    cards.BloodfenRaptor,
    cards.BoulderfistOgre,
    cards.MagmaRager,
    cards.Nightblade,
    cards.NoviceEngineer,
    cards.MurlocRaider,
    cards.SpiderTank,
    cards.LeperGnome,
    cards.FrostwolfGrunt,
    cards.ChillwindYeti,
    cards.ElvenArcher,
    cards.OgreMagi,
    cards.SilverHandKnight,
    cards.Spellbreaker,
    cards.ArgentCommander,
    cards.AzureDrake,
    cards.GadgetzanAuctioneer,
    cards.KnifeJuggler,
    cards.CrazedAlchemist,
    cards.AcolyteofPain,
    cards.BigGameHunter,
    cards.HauntedCreeper,
    cards.NerubarWeblord,
    cards.NerubianEgg,
    cards.Deathlord,
    cards.ShadeofNaxxramas,
    cards.StoneskinGargoyle,
    cards.Abomination,
    cards.AnnoyoTron,
    cards.ClockworkGnome,
    cards.Mechwarper,
    cards.HarvestGolem,
    cards.TinkertownTechnician,
    cards.MechanicalYeti,
    cards.PilotedShredder,
    cards.BlackwingTechnician,
    cards.BlackwingCorruptor,
    cards.ArgentHorserider,
    cards.NorthSeaKraken,
    cards.TwilightGuardian,
    cards.Kodorider,
    cards.MasterJouster,
    cards.Sylvanas,
    cards.Toshley,
    cards.EmperorThaurissan,
    cards.Nefarian,
    cards.DrBoom,
    cards.Ragnaros,
    cards.Alexstrasza,
    cards.Deathwing,
    cards.NexusChampionSaraad,
    cards.RenoJackson,
    cards.EliseStarseeker,
    cards.BloodmageThalnos,
    cards.PollutedHoarder,
    cards.CorruptedHealbot,
    cards.EaterofSecrets,
    cards.ValidatedDoomsayer,
    cards.HoggerScourgeofElwynn,
    cards.YShaarjRageUnbound,
    cards.CThun,
    cards.BeckonerofEvil,
    cards.CThunsChosen,
    cards.TwilightElder,
    cards.ArcaneGiant,
    cards.SergeantSally,
    
    cards.DonHanCho,
    
    cards.JadeSpirit,
    cards.LotusAgents,
    cards.AyaBlackpaw,
    
    cards.KabalChemist,

    cards.Fireball,
    cards.ArcaneMissiles,
    cards.Polymorph,
    cards.Frostbolt,
    cards.ManaWyrm,
    cards.UnstablePortal,
    cards.GoblinBlastmage,
    cards.Snowchugger,
    cards.MirrorEntity,
    cards.Duplicate,
    cards.ArcaneExplosion,
    cards.Flamestrike,
    cards.ConeofCold,
    cards.Flamecannon,
    cards.FrostNova,
    cards.MirrorImage,
    cards.ArchmageAntonidas,

    cards.Execute,
    cards.Whirlwind,
    cards.ArcaniteReaper,
    cards.GrimPatron,
    cards.FrothingBerserker,
    cards.BattleRage,
    cards.Cleave,
    cards.BloodWarriors,

    cards.IronSensei,
    cards.Backstab,
    cards.Sap,
    cards.Shiv,
    cards.FanofKnives,
    cards.Sprint,
    cards.AnubarAmbusher,

    cards.Crackle,
    cards.LavaBurst,
    cards.WhirlingZapoMatic,
    cards.FeralSpirit,
    cards.ForkedLightning,
    cards.UnboundElemental,
    cards.AlAkirtheWindlord,

    cards.AnimalCompanion,
    cards.MultiShot,
    cards.UnleashTheHounds,
    cards.ExplosiveShot,
    cards.ArcaneShot,
    cards.CobraShot,
    cards.KingsElekk,
    cards.DeadlyShot,
    cards.HuntersMark,
    cards.CoreRager,
    cards.GiantSandworm,
    cards.KingKrush,
    cards.Gahzrilla,

    cards.Innervate,
    cards.Swipe,
    cards.Moonfire,
    cards.WildGrowth,
    cards.JadeBlossom,
    cards.LivingRoots,
    cards.RavenIdol,
    cards.Wrath,
    cards.JadeIdol,
    cards.Nourish,
    cards.TreeofLife,
    cards.DruidoftheFlame,
    cards.JadeBehemoth,
    cards.KlaxxiAmberWeaver,
    cards.AncientofLore,
    cards.AncientofWar,
    cards.Cenarius,
    cards.Malorne,

    cards.Darkbomb,
    cards.ShadowBolt,
    cards.MortalCoil,
    cards.Voidwalker,
    cards.Succubus,
    cards.Shadowflame,
    cards.LordJaraxxus,
    cards.MalGanis,

    cards.StandAgainstDarkness,
    cards.AldorPeacekeeper,
    cards.Equality,
    cards.AvengingWrath,
    cards.BlessingofKings,
    cards.GuardianofKings,
    cards.WarhorseTrainer,
    cards.HammerofWrath,
    cards.MurlocKnight,
    cards.TirionFordring,
    // cards.BolvarFordragon,

    cards.PowerWordShield,
    cards.ShadowWordDeath,
    cards.ShadowWordPain,
    cards.HolyNova,
    cards.Entomb,
    cards.VelensChosen,
    cards.HolyFire,
    cards.Resurrect,
    cards.Shadowform,
    cards.NorthshireCleric,
    cards.TwilightWhelp,
    cards.WyrmrestAgent,
    
    ];
};

var classCards = module.exports.classCards = function(className) {
    var cardList = [];
    var allCardsList = allCards();
    for(var i in allCardsList) {
        var card = allCardsList[i]();
        if(card.cardClass) {
            for(var j in card.cardClass) {
                var cardClass = card.cardClass[j];
                if(cardClass == className) {
                    cardList.push(card.card);
                }
            }
        }
    }
    return cardList;
};