var cards = require('./cards.js');
var cardLists = require('./cardlists.js');

module.exports.basicDeck = function() {
    return [
        cards.MurlocRaider(),
        cards.Kodorider(),
        cards.MasterJouster(),
        cards.ArcaneGiant(),
        cards.BigGameHunter(),
        cards.HoggerScourgeofElwynn(),
        cards.FacelessManipulator(),
        cards.MasterJouster(),
        cards.KnifeJuggler(),
        cards.Alexstrasza(),
        cards.Sylvanas(),
        cards.EmperorThaurissan(),
        cards.CThun(),
        cards.Ragnaros(),
        cards.NexusChampionSaraad(),
        cards.YShaarjRageUnbound(),
        cards.PollutedHoarder(),
        cards.CorruptedHealbot(),
        cards.ValidatedDoomsayer(),
        cards.AbusiveSergeant(),
        cards.AbusiveSergeant()
    ];
};

module.exports.basicMage = function() {
    return [
        cards.Fireball(),
        cards.Fireball(),
        cards.Frostbolt(),
        cards.Frostbolt(),
        cards.ArcaneMissiles(),
        cards.Polymorph(),
        cards.ArcaneIntellect(),
        cards.MirrorEntity(),
        cards.Duplicate(),
        cards.Vaporize(),
        cards.Vaporize(),
        cards.ManaWyrm(),
        cards.UnstablePortal(),
        cards.UnstablePortal(),
        cards.Spellslinger(),
        cards.Spellslinger(),
        cards.Flamecannon(),
        cards.HoggerScourgeofElwynn(),
        cards.Flamestrike(),
        cards.ArchmageAntonidas(),
        cards.YoggSaronHopesEnd(),
        cards.BeckonerofEvil(),
        cards.TwilightElder(),
        cards.TwilightElder(),
        cards.CThun(),
        cards.NexusChampionSaraad(),
        cards.ArcaneGiant(),
        cards.YShaarjRageUnbound(),
        cards.CorruptedHealbot(),
        cards.ValidatedDoomsayer(),
    ];
};

module.exports.RenoMage = function() {
    return [
        cards.ForbiddenFlame(),
        cards.ArcaneBlast(),
        // cards.BabblingBook(),
        cards.MirrorImage(),
        cards.Frostbolt(),
        cards.ArcaneIntellect(),
        // cards.Flamewaker(),
        // cards.ForgottenTorch(),
        cards.IceBlock(),
        // cards.VolcanicPotion(),
        cards.Fireball(),
        cards.Polymorph(),
        // cards.WaterElemental(),
        cards.ArchmageAntonidas(),
        cards.Flamestrike(),
        cards.Rhonin(),
        // cards.MistressofMixtures(),
        // cards.AcidicSwampOoze(),
        cards.BloodmageThalnos(),
        // cards.Doomsayer(),
        // cards.LootHoarder(),
        // cards.BrannBronzebeard(),
        // cards.Barnes(),
        // cards.InfestedTauren(),
        // cards.Kazakus(),
        cards.AzureDrake(),
        cards.EmperorThaurissan(),
        cards.RenoJackson(),
        cards.Sylvanas(),
        cards.NZoththeCorruptor()
    ];
};

module.exports.basicWarrior = function() {
    return [
        cards.Execute(),
        cards.Execute(),
        cards.Whirlwind(),
        cards.Whirlwind(),
        cards.GrimPatron(),
        cards.GrimPatron(),
        cards.ArcaniteReaper(),
        cards.ArcaniteReaper(),
        cards.FrothingBerserker(),
        cards.FrothingBerserker(),
        cards.AcolyteofPain(),
        cards.AcolyteofPain(),
        cards.ArcaneGiant(),
        cards.PilotedShredder(),
        cards.HoggerScourgeofElwynn(),
        cards.BloodWarriors(),
        cards.BloodWarriors(),
        cards.FacelessManipulator(),
        cards.YoggSaronHopesEnd(),
        cards.BeckonerofEvil(),
        cards.TwilightElder(),
        cards.TwilightElder(),
        cards.EmperorThaurissan(),
        cards.CThun(),
        cards.Ragnaros(),
        cards.NexusChampionSaraad(),
        cards.YShaarjRageUnbound(),
        cards.PollutedHoarder(),
        cards.CorruptedHealbot(),
        cards.ValidatedDoomsayer(),
    ];
};

module.exports.GoonsWarrior = function() {
    return [
        cards.IKnowAGuy(),
        cards.IKnowAGuy(),
        cards.ShieldSlam(),
        cards.Execute(),
        cards.Execute(),
        cards.FieryWarAxe(),
        cards.FieryWarAxe(),
        cards.PublicDefender(),
        cards.StolenGoods(),
        cards.FrothingBerserker(),
        cards.FrothingBerserker(),
        cards.RavagingGhoul(),
        cards.RavagingGhoul(),
        cards.ShieldBlock(),
        cards.ShieldBlock(),
        cards.BloodhoofBrave(),
        cards.BloodhoofBrave(),
        cards.GrimyGadgeteer(),
        cards.GrimyGadgeteer(),
        cards.AlleyArmorsmith(),
        cards.AlleyArmorsmith(),
        cards.Brawl(),
        cards.Brawl(),
        cards.AcolyteofPain(),
        cards.AcolyteofPain(),
        cards.GrimestreetSmuggler(),
        cards.GrimestreetSmuggler(),
        // cards.Doppelgangster(),
        cards.DonHanCho(),
        cards.ArchThiefRafaam(),
    ];
};

module.exports.basicRogue = function() {
    return [
        cards.Backstab(),
        cards.Backstab(),
        cards.Sap(),
        cards.Sap(),
        cards.Shiv(),
        cards.FanofKnives(),
        cards.FanofKnives(),
        cards.Sprint(),
        cards.Sprint(),
        cards.Kodorider(),
        cards.KnifeJuggler(),
        cards.PilotedShredder(),
        cards.PilotedShredder(),
        cards.FrostwolfGrunt(),
        cards.MasterJouster(),
        cards.ArcaneGiant(),
        cards.HoggerScourgeofElwynn(),
        cards.FacelessManipulator(),
        cards.FacelessManipulator(),
        cards.YoggSaronHopesEnd(),
        cards.BeckonerofEvil(),
        cards.TwilightElder(),
        cards.TwilightElder(),
        cards.CThun(),
        cards.Ragnaros(),
        cards.NexusChampionSaraad(),
        cards.YShaarjRageUnbound(),
        cards.PollutedHoarder(),
        cards.CorruptedHealbot(),
        cards.ValidatedDoomsayer(),
    ];
};

module.exports.DragonRogue = function() {
    return [
        cards.Backstab(),
        cards.Backstab(),
        // cards.Swashburglar(),
        // cards.Eviscerate(),
        // cards.Eviscerate(),
        cards.Sap(),
        cards.Sap(),
        // cards.UndercityHuckster(),
        // cards.UndercityHuckster(),
        cards.FanofKnives(),
        cards.FanofKnives(),
        // cards.ShadowStrike(),
        // cards.Si7Agent(),
        // cards.Si7Agent(),
        // cards.DarkIronSkulker(),
        cards.BloodmageThalnos(),
        // cards.FaerieDragon(),
        // cards.FaerieDragon(),
        // cards.EarthenRingFarseer(),
        // cards.EarthenRingFarseer(),
        cards.TwilightGuardian(),
        cards.TwilightGuardian(),
        cards.AzureDrake(),
        cards.AzureDrake(),
        cards.BlackwingCorruptor(),
        cards.BlackwingCorruptor(),
        // cards.BookWyrm(),
        // cards.DrakonidCrusher(),
        // cards.DrakonidCrusher(),
        cards.Ragnaros()
    ];
};

module.exports.basicShaman = function() {
    return [
        cards.Crackle(),
        cards.Crackle(),
        cards.LavaBurst(),
        cards.WhirlingZapoMatic(),
        cards.WhirlingZapoMatic(),
        cards.FeralSpirit(),
        cards.FeralSpirit(),
        cards.ForkedLightning(),
        cards.ForkedLightning(),
        cards.UnboundElemental(),
        cards.UnboundElemental(),
        cards.AlAkirtheWindlord(),
        cards.Kodorider(),
        cards.KnifeJuggler(),
        cards.KnifeJuggler(),
        cards.ArcaneGiant(),
        cards.PilotedShredder(),
        cards.YoggSaronHopesEnd(),
        cards.BeckonerofEvil(),
        cards.TwilightElder(),
        cards.TwilightElder(),
        cards.HoggerScourgeofElwynn(),
        cards.Sylvanas(),
        cards.EmperorThaurissan(),
        cards.CThun(),
        cards.NexusChampionSaraad(),
        cards.YShaarjRageUnbound(),
        cards.PollutedHoarder(),
        cards.CorruptedHealbot(),
        cards.ValidatedDoomsayer(),
    ];
};

module.exports.JadeShaman = function() {
    return [
        // cards.LightningBolt(),
        // cards.LightningBolt(),
        // cards.TunnelTrog(),
        // cards.TunnelTrog(),
        // cards.JadeClaws(),
        // cards.JadeClaws(),
        // cards.MaelstromPortal(),
        // cards.MaelstromPortal(),
        // cards.TotemGolem(),
        // cards.TotemGolem(),
        cards.FeralSpirit(),
        // cards.Hex(),
        // cards.Hex(),
        // cards.LightningStorm(),
        // cards.LightningStorm(),
        // cards.ManaTideTotem(),
        // cards.ManaTideTotem(),
        // cards.JadeLightning(),
        // cards.ThunderBluffValiant(),
        // cards.ThunderBluffValiant(),
        // cards.ThingFromBelow(),
        // cards.ThingFromBelow(),
        cards.JadeSpirit(),
        cards.JadeSpirit(),
        cards.AzureDrake(),
        cards.AzureDrake(),
        cards.AyaBlackpaw(),
        cards.Ragnaros()
    ];
};

module.exports.basicHunter = function() {
    return [
        cards.AnimalCompanion(),
        cards.AnimalCompanion(),
        cards.MultiShot(),
        cards.UnleashTheHounds(),
        cards.UnleashTheHounds(),
        cards.ExplosiveShot(),
        cards.ExplosiveShot(),
        cards.ArcaneShot(),
        cards.DeadlyShot(),
        cards.HuntersMark(),
        cards.HuntersMark(),
        cards.KingsElekk(),
        cards.KingsElekk(),
        cards.GiantSandworm(),
        cards.GiantSandworm(),
        cards.HoggerScourgeofElwynn(),
        cards.PilotedShredder(),
        cards.MasterJouster(),
        cards.ArcaneGiant(),
        cards.YoggSaronHopesEnd(),
        cards.BeckonerofEvil(),
        cards.TwilightElder(),
        cards.TwilightElder(),
        cards.CThun(),
        cards.Ragnaros(),
        cards.NexusChampionSaraad(),
        cards.YShaarjRageUnbound(),
        cards.PollutedHoarder(),
        cards.CorruptedHealbot(),
        cards.ValidatedDoomsayer(),
    ];
};

module.exports.BeastHunter = function() {
    return [
        // cards.Alleycat(),
        // cards.Alleycat(),
        cards.HuntersMark(),
        // cards.Tracking(),
        // cards.KindlyGrandmother(),
        // cards.KindlyGrandmother(),
        // cards.QuickShot(),
        // cards.QuickShot(),
        // cards.ScavengingHyena(),
        // cards.ScavengingHyena(),
        // cards.TroggBeastrager(),
        // cards.TroggBeastrager(),
        // cards.KillCommand(),
        // cards.KillCommand(),
        // cards.RatPack(),
        // cards.RatPack(),
        // cards.ShakyZipgunner(),
        // cards.ShakyZipgunner(),
        cards.UnleashTheHounds(),
        // cards.DispatchKodo(),
        // cards.DispatchKodo(),
        // cards.Houndmaster(),
        // cards.Houndmaster(),
        // cards.TundraRhino(),
        // cards.TundraRhino(),
        // cards.SavannahHighmane(),
        // cards.SavannahHighmane(),
        // cards.DireWolfAlpha(),
        // cards.DireWolfAlpha(),
        // cards.LeeroyJenkins()
    ];
};

module.exports.basicDruid = function() {
    return [
        cards.Swipe(),
        cards.Swipe(),
        cards.DruidoftheFlame(),
        cards.Innervate(),
        cards.Innervate(),
        cards.Moonfire(),
        cards.TreeofLife(),
        cards.Cenarius(),
        cards.Malorne(),
        cards.Kodorider(),
        cards.KnifeJuggler(),
        cards.PilotedShredder(),
        cards.PilotedShredder(),
        cards.KlaxxiAmberWeaver(),
        cards.ArcaneGiant(),
        cards.HoggerScourgeofElwynn(),
        cards.KlaxxiAmberWeaver(),
        cards.FacelessManipulator(),
        cards.AnnoyoTron(),
        cards.YoggSaronHopesEnd(),
        cards.BeckonerofEvil(),
        cards.TwilightElder(),
        cards.TwilightElder(),
        cards.CThun(),
        cards.Ragnaros(),
        cards.NexusChampionSaraad(),
        cards.YShaarjRageUnbound(),
        cards.PollutedHoarder(),
        cards.CorruptedHealbot(),
        cards.ValidatedDoomsayer(),
    ];
};

module.exports.JadeDruid = function() {
    return [
        cards.Innervate(),
        cards.Innervate(),
        cards.LivingRoots(),
        cards.JadeIdol(),
        cards.JadeIdol(),
        cards.RavenIdol(),
        cards.RavenIdol(),
        cards.WildGrowth(),
        cards.WildGrowth(),
        cards.Wrath(),
        cards.Wrath(),
        cards.LotusAgents(),
        cards.LotusAgents(),
        cards.JadeBlossom(),
        cards.JadeBlossom(),
        cards.FandralStaghelm(),
        cards.Swipe(),
        cards.Swipe(),
        cards.Nourish(),
        cards.Nourish(),
        cards.JadeBehemoth(),
        cards.JadeBehemoth(),
        cards.AncientofWar(),
        cards.AncientofWar(),
        cards.JadeSpirit(),
        cards.JadeSpirit(),
        cards.AzureDrake(),
        cards.AzureDrake(),
        cards.AyaBlackpaw(),
        cards.GadgetzanAuctioneer(),
    ];
};

module.exports.basicWarlock = function() {
    return [
        cards.Voidwalker(),
        cards.Voidwalker(),
        cards.MortalCoil(),
        cards.MortalCoil(),
        cards.Darkbomb(),
        cards.Darkbomb(),
        cards.Succubus(),
        cards.LordJaraxxus(),
        cards.MalGanis(),
        cards.Kodorider(),
        cards.KnifeJuggler(),
        cards.KnifeJuggler(),
        cards.PilotedShredder(),
        cards.MasterJouster(),
        cards.HoggerScourgeofElwynn(),
        cards.ArcaneGiant(),
        cards.FacelessManipulator(),
        cards.AnnoyoTron(),
        cards.YoggSaronHopesEnd(),
        cards.BeckonerofEvil(),
        cards.TwilightElder(),
        cards.TwilightElder(),
        cards.CThun(),
        cards.Ragnaros(),
        cards.Deathwing(),
        cards.NexusChampionSaraad(),
        cards.YShaarjRageUnbound(),
        cards.PollutedHoarder(),
        cards.CorruptedHealbot(),
        cards.ValidatedDoomsayer(),
    ];
};

module.exports.RenoWarlock = function() {
    return [
        cards.MortalCoil(),
        // cards.PowerOverwhelming(),
        // cards.DarkPeddler(),
        // cards.Demonwrath(),
        // cards.ImpGangBoss(),
        cards.ShadowBolt(),
        // cards.Hellfire(),
        cards.Shadowflame(),
        // cards.SiphonSoul(),
        // cards.AbyssalEnforcer(),
        // cards.TwistingNether(),
        cards.LordJaraxxus(),
        // cards.AcidicSwampOoze(),
        // cards.DirtyRat(),
        // cards.Doomsayer(),
        // cards.SunfuryProtector(),
        // cards.BrannBronzebeard(),
        // cards.EarthenRingFarseer(),
        // cards.MindControlTech(),
        // cards.FacelessShambler(),
        // cards.Kazakus(),
        // cards.RefreshmentVendor(),
        // cards.TwilightDrake(),
        cards.FacelessManipulator(),
        // cards.LeeroyJenkins(),
        // cards.SecondRateBruiser(),
        cards.EmperorThaurissan(),
        cards.RenoJackson(),
        cards.Sylvanas(),
        // cards.MountainGiant()
    ];    
};

module.exports.basicPaladin = function() {
    return [
        cards.BlessingofKings(),
        cards.BlessingofKings(),
        cards.AvengingWrath(),
        cards.Equality(),
        cards.WarhorseTrainer(),
        cards.WarhorseTrainer(),
        cards.HammerofWrath(),
        cards.AldorPeacekeeper(),
        cards.AldorPeacekeeper(),
        cards.MurlocKnight(),
        cards.StandAgainstDarkness(),
        cards.StandAgainstDarkness(),
        cards.TirionFordring(),
        cards.KnifeJuggler(),
        cards.HoggerScourgeofElwynn(),
        cards.PilotedShredder(),
        cards.YoggSaronHopesEnd(),
        cards.BeckonerofEvil(),
        cards.TwilightElder(),
        cards.TwilightElder(),
        cards.ArcaneGiant(),
        cards.EmperorThaurissan(),
        cards.Sylvanas(),
        cards.CThun(),
        cards.Ragnaros(),
        cards.NexusChampionSaraad(),
        cards.YShaarjRageUnbound(),
        cards.PollutedHoarder(),
        cards.CorruptedHealbot(),
        cards.ValidatedDoomsayer(),
    ];
};

module.exports.MurlocPaladin = function() {
    return [
        // cards.GrimscaleChum(),
        // cards.GrimscaleChum(),
        // cards.SmugglersRun(),
        // cards.SmugglersRun(),
        // cards.VilefinInquisitor(),
        // cards.VilefinInquisitor(),
        // cards.GrimestreetOutfitter(),
        // cards.GrimestreetOutfitter(),
        // cards.DivineFavor(),
        // cards.SmallTimeRecruits(),
        // cards.SmallTimeRecruits(),
        cards.MurlocKnight(),
        cards.MurlocKnight(),
        // cards.GrimscaleOracle(),
        // cards.GrimscaleOracle(),
        // cards.MurlocTidecaller(),
        // cards.MurlocTidecaller(),
        // cards.SirFinleyMrrgglton(),
        // cards.BilefinTidehunter(),
        // cards.BlowgillSniper(),
        // cards.BluegillWarrior(),
        // cards.MurlocTidehunter(),
        // cards.MurlocTidehunter(),
        // cards.BrannBronzebeard(),
        // cards.ColdlightSeer(),
        // cards.ColdlightSeer(),
        // cards.MurlocWarleader(),
        // cards.MurlocWarleader(),
        // cards.FinjaTheFlyingStar()
    ];
}

module.exports.basicPriest = function() {
    return [
        cards.HolyNova(),
        cards.HolyNova(),
        cards.ShadowWordPain(),
        cards.ShadowWordPain(),
        cards.PowerWordShield(),
        cards.PowerWordShield(),
        cards.NorthshireCleric(),
        cards.NorthshireCleric(),
        cards.Kodorider(),
        cards.KnifeJuggler(),
        cards.AnnoyoTron(),
        cards.Shadowform(),
        cards.PilotedShredder(),
        cards.Resurrect(),
        cards.Shadowform(),
        cards.Resurrect(),
        cards.HoggerScourgeofElwynn(),
        cards.ArcaneGiant(),
        cards.ArcaneGiant(),
        cards.BeckonerofEvil(),
        cards.YoggSaronHopesEnd(),
        cards.TwilightElder(),
        cards.TwilightElder(),
        cards.CThun(),
        cards.Ragnaros(),
        cards.NexusChampionSaraad(),
        cards.YShaarjRageUnbound(),
        cards.PollutedHoarder(),
        cards.CorruptedHealbot(),
        cards.ValidatedDoomsayer(),
    ];
};

module.exports.RenoPriest = function() {
    return [
        cards.NorthshireCleric(),
        // cards.PintSizePotion(),
        cards.PowerWordShield(),
        cards.TwilightWhelp(),
        cards.ShadowWordPain(),
        // cards.KabalTalonpriest(),
        cards.ShadowWordDeath(),
        // cards.DrakonidOperative(),
        cards.HolyNova(),
        // cards.KabalSongstealer(),
        // cards.RazaTheChained(),
        // cards.CabalShadowPriest(),
        // cards.DragonfirePotion(),
        cards.Entomb(),
        // cards.AcidicSwampOoze(),
        // cards.DirtyRat(),
        // cards.Doomsayer(),
        // cards.NetherspiteHistorian(),
        // cards.BrannBronzebeard(),
        // cards.KabalCourier(),
        // cards.MindControlTech(),
        cards.KabalChemist(),
        // cards.Kazakus(),
        cards.TwilightGuardian(),
        cards.AzureDrake(),
        cards.BlackwingCorruptor(),
        // cards.BookWyrm(),
        cards.RenoJackson(),
        // cards.Chillmaw(),
        // cards.Ysera()
    ];
};

module.exports.MechMage = function() {
    return [
        cards.ClockworkGnome(),
        cards.ClockworkGnome(),
        cards.ManaWyrm(),
        cards.ManaWyrm(),
        cards.Frostbolt(),
        cards.Frostbolt(),
        cards.AnnoyoTron(),
        cards.AnnoyoTron(),
        cards.Mechwarper(),
        cards.Mechwarper(),
        cards.Snowchugger(),
        cards.Snowchugger(),
        cards.HarvestGolem(),
        cards.HarvestGolem(),
        cards.SpiderTank(),
        cards.SpiderTank(),
        cards.TinkertownTechnician(),
        cards.TinkertownTechnician(),
        cards.Fireball(),
        cards.Fireball(),
        cards.Polymorph(),
        cards.Polymorph(),
        cards.GoblinBlastmage(),
        cards.GoblinBlastmage(),
        cards.MechanicalYeti(),
        cards.Toshley(),
        cards.Sylvanas(),
        cards.ArchmageAntonidas(),
        cards.DrBoom(),
        cards.Ragnaros(),
    ];
};

module.exports.DragonPriest = function() {
    return [
        cards.Resurrect(),
        cards.HolySmite(),
        cards.NorthshireCleric(),
        cards.NorthshireCleric(),
        cards.TwilightWhelp(),
        cards.TwilightWhelp(),
        cards.WyrmrestAgent(),
        cards.WyrmrestAgent(),
        cards.ShadowWordDeath(),
        cards.ShadowWordDeath(),
        cards.VelensChosen(),
        cards.VelensChosen(),
        cards.BlackwingTechnician(),
        cards.BlackwingTechnician(),
        cards.DarkCultist(),
        cards.TwilightGuardian(),
        cards.TwilightGuardian(),
        cards.HolyNova(),
        cards.HolyNova(),
        cards.AzureDrake(),
        cards.AzureDrake(),
        cards.BlackwingCorruptor(),
        cards.BlackwingCorruptor(),
        cards.Entomb(),
        cards.HolyFire(),
        // cards.JusticarTrueheart(),
        cards.Sylvanas(),
        // cards.RendBlackhand(),
        cards.Nefarian(),
        // cards.Ysera()
    ];
};

module.exports.Nerzhul = function() {
    return cardLists.setCards("Icecrown Citadel");
};

// Adventure bosses

module.exports.AnubRekhan = function() {
    return [
        cards.MortalCoil(),
        cards.MortalCoil(),
        cards.Deathcharger(),
        cards.Deathcharger(),
        cards.Frostbolt(),
        cards.Frostbolt(),
        cards.CrazedAlchemist(),
        cards.CrazedAlchemist(),
        cards.HauntedCreeper(),
        cards.HauntedCreeper(),
        cards.NerubarWeblord(),
        cards.NerubarWeblord(),
        cards.NerubianEgg(),
        cards.NerubianEgg(),
        cards.ShadowBolt(),
        cards.ShadowBolt(),
        cards.Deathlord(),
        cards.Deathlord(),
        cards.ShadeofNaxxramas(),
        cards.ShadeofNaxxramas(),
        cards.StoneskinGargoyle(),
        cards.StoneskinGargoyle(),
        cards.Shadowflame(),
        cards.AnubarAmbusher(),
        cards.AnubarAmbusher(),
        cards.Abomination(),
        cards.Abomination(),
        cards.LocustSwarm(),
        cards.LocustSwarm(),
        cards.LocustSwarm(),
    ];
};

module.exports.GrandWidowFaerlina = function() {
    return [
        cards.AbusiveSergeant(),
        cards.AbusiveSergeant(),
        cards.AcolyteofPain(),
        cards.AcolyteofPain(),
        cards.BattleRage(),
        cards.BattleRage(),
        cards.CultMaster(),
        cards.DancingSwords(),
        cards.DancingSwords(),
        cards.DarkCultist(),
        cards.DarkCultist(),
        cards.Deathcharger(),
        cards.Deathcharger(),
        // cards.Hellfire(),
        // cards.Hellfire(),
        // cards.InnerRage(),
        // cards.InnerRage(),
        // cards.Necroknight(),
        // cards.Necroknight(),
        cards.NerubianEgg(),
        cards.NerubianEgg(),
        // cards.Rampage(),
        // cards.Rampage(),
        // cards.Undertaker(),
        // cards.Undertaker(),
        // cards.WorshipperN(),
        // cards.WorshipperN(),
        // cards.WorshipperN(),
        // cards.WorshipperN(),
        // cards.WorshipperN()
    ];
};

module.exports.GrandWidowFaerlina_Heroic = function() {
    return [
        cards.AbusiveSergeant(),
        cards.AbusiveSergeant(),
        cards.AcolyteofPain(),
        cards.AcolyteofPain(),
        cards.BattleRage(),
        cards.BattleRage(),
        cards.CultMaster(),
        cards.DancingSwords(),
        cards.DancingSwords(),
        cards.DarkCultist(),
        cards.DarkCultist(),
        cards.Deathcharger(),
        cards.Deathcharger(),
        // cards.Hellfire(),
        // cards.Hellfire(),
        // cards.InnerRage(),
        // cards.InnerRage(),
        // cards.Necroknight(),
        // cards.Necroknight(),
        cards.NerubianEgg(),
        cards.NerubianEgg(),
        // cards.Rampage(),
        // cards.Rampage(),
        // cards.Undertaker(),
        // cards.Undertaker(),
        // cards.WorshipperH(),
        // cards.WorshipperH(),
        // cards.WorshipperH(),
        // cards.WorshipperH(),
        // cards.WorshipperH()
    ];
};

// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Custom Sets

// These will be adventure boss decks, or decks using custom classes.

module.exports.C_LadyDeathwhisper_Normal = function() {
    return [
        cards.Frostbolt(),
        cards.Frostbolt(),
        cards.Frostbolt(),
        cards.Frostbolt(),
        cards.Frostbolt(),
        cards.Frostbolt(),
        cards.Frostbolt(),
        cards.ShadowBolt(),
        cards.ShadowBolt(),
        cards.ShadowBolt(),
        cards.ShadowBolt(),
        cards.ShadowBolt(),
        cards.ShadowBolt(),
        cards.ShadowBolt(),
        cards.C_CultAdherent(),
        cards.C_CultAdherent(),
        cards.C_CultAdherent(),
        cards.C_CultAdherent(),
        cards.C_CultAdherent(),
        cards.C_DarkEmpowerment(),
        cards.C_DarkEmpowerment(),
        cards.C_CultFanatic_Normal(),
        cards.C_CultFanatic_Normal(),
        cards.C_CultFanatic_Normal(),
        cards.C_CultFanatic_Normal(),
        cards.C_CultFanatic_Normal(),
        cards.C_DarkTransformation(),
        cards.C_DarkTransformation(),
        cards.BloodmageThalnos(),
        cards.Loatheb()
    ];
};

module.exports.C_OrgrimsHammer_Heroic = function() {
    return [
        cards.C_CannonBlast(),
        cards.C_CannonBlast(),
        cards.C_CannonBlast(),
        cards.C_CannonBlast(),
        cards.C_CannonBlast(),
        cards.C_IncineratingBlast(),
        cards.C_IncineratingBlast(),
        cards.C_IncineratingBlast(),
        cards.C_IncineratingBlast(),
        cards.C_IncineratingBlast(),
        cards.C_IncineratingBlast(),
        cards.C_Repairs(),
        cards.C_Fortify(),
        cards.C_Fortify(),
        cards.C_Fortify(),
        cards.C_Fortify(),
        // cards.C_BoardingParty(),
        // cards.C_BoardingParty(),
        // cards.C_BoardingParty(),
        // cards.C_BoardingParty(),
        // cards.C_BoardingParty(),
        // cards.C_BoardingParty(),
        // cards.C_BoardingParty(),
        // cards.C_BoardingParty(),
        cards.C_Reload(),
        cards.C_Reload(),
        cards.C_Reload(),
        cards.C_Reload(),
        cards.C_Reload(),
        cards.C_Reload(),
    ];
};

module.exports.C_Skybreaker_Heroic = function() {
    return [
        cards.C_CannonBlast(),
        cards.C_CannonBlast(),
        cards.C_CannonBlast(),
        cards.C_CannonBlast(),
        cards.C_CannonBlast(),
        cards.C_CannonBlast(),
        cards.C_CannonBlast(),
        cards.C_CannonBlast(),
        cards.C_CannonBlast(),
        cards.C_CannonBlast(),
        cards.C_CannonBlast(),
        cards.C_IncineratingBlast(),
        cards.C_IncineratingBlast(),
        cards.C_IncineratingBlast(),
        cards.C_Repairs(),
        cards.C_Repairs(),
        cards.C_Repairs(),
        cards.C_Repairs(),
        cards.C_Repairs(),
        cards.C_Fortify(),
        // cards.C_BoardingParty(),
        // cards.C_BoardingParty(),
        // cards.C_BoardingParty(),
        cards.C_Reload(),
        cards.C_Reload(),
        cards.C_Reload(),
        cards.C_Reload(),
        cards.C_Reload(),
        cards.C_Reload(),
        cards.C_Reload(),
    ];
};

// ++++++++++++++++++++++++++++++++++++++++++++

// Sad Mystery

module.exports.Arthas1 = function() { // missions 1-3
    return [
        cards.Arthas_ValiantFootman(),
        cards.Arthas_ValiantFootman(),
        cards.Arthas_ValiantFootman(),
        cards.Arthas_ValiantFootman(),
        cards.Arthas_ValiantFootman(),
        cards.Arthas_ValiantFootman(),
        cards.Arthas_ValiantFootman(),
        cards.Arthas_DwarvenRifleman(),
        cards.Arthas_DwarvenRifleman(),
        cards.Arthas_DwarvenRifleman(),
        cards.Arthas_DwarvenRifleman(),
        cards.Arthas_DwarvenRifleman(),
        cards.Arthas_DwarvenRifleman(),
        cards.Arthas_DwarvenRifleman(),
        cards.Arthas_Devotion(),
        cards.Arthas_Devotion(),
        cards.Arthas_Devotion(),
        cards.Arthas_HolyLight(),
        cards.Arthas_HolyLight(),
        cards.Arthas_HolyLight(),
        cards.Arthas_HolyLight(),
        cards.Arthas_HolyLight(),
        cards.Arthas_HolyLight(),
        cards.Arthas_HolyLight(),
        cards.Arthas_Retribution(),
        cards.Arthas_HammerofJustice(),
        cards.Arthas_HammerofJustice(),
        cards.Arthas_HammerofJustice(),
        cards.Arthas_HammerofJustice(),
        cards.Arthas_BladeofWrath()
    ];
};

module.exports.Arthas2 = function() { // missions 4-5
    return [
        cards.Arthas_ValiantFootman(),
        cards.Arthas_ValiantFootman(),
        cards.Arthas_ValiantFootman(),
        cards.Arthas_ValiantFootman(),
        cards.Arthas_ValiantFootman(),
        cards.Arthas_ValiantFootman(),
        cards.Arthas_DwarvenRifleman(),
        cards.Arthas_DwarvenRifleman(),
        cards.Arthas_DwarvenRifleman(),
        cards.Arthas_DwarvenRifleman(),
        cards.Arthas_DwarvenRifleman(),
        cards.Arthas_DwarvenRifleman(),
        cards.Arthas_Knight(),
        cards.Arthas_Knight(),
        cards.Arthas_Knight(),
        cards.Arthas_Knight(),
        cards.Arthas_ElvenPriest(),
        cards.Arthas_ElvenPriest(),
        cards.Arthas_ElvenPriest(),
        cards.Arthas_Sorceress(),
        cards.Arthas_Sorceress(),
        cards.Arthas_HolyLight(),
        cards.Arthas_HolyLight(),
        cards.Arthas_HolyLight(),
        cards.Arthas_HolyLight(),
        cards.Arthas_Devotion(),
        cards.Arthas_Retribution(),
        cards.Arthas_Retribution(),
        cards.Arthas_BladeofWrath(),
        cards.Arthas_BladeofWrath()
    ];
};